### ISSUE TITLE
Lavaland Monsters AI broken.

### ISSUE THREAD

**Issue by Obliii** [pariahstation/Pariah-Station#689]
## Round ID:

Lavaland monsters don't move when they are in a attack state. 
I.E. Goaliths move one tile, then never move again and only use their ability. 

## Testmerges:

N/A

## Reproduction:

Hit goalith once, watch it never move.

**Comment by SabreML** [comment]
As far as I can tell this is a base TG issue. Same problem on both codebases.

**Comment by SabreML** [comment]
Update: TG has a PR open now which fixes this issue. I'll port it over if it gets merged.
