### ISSUE TITLE
[Mapping?] HoP Locker on Meta has no Civil Budget Card for the Service Department.

### ISSUE THREAD

**Issue by ta3370** [pariahstation/Pariah-Station#712]
## Round ID:
[60](https://scrubby.melonmesa.com/round/60)

## Testmerges:
#708 
#704 
#699 
#688 
#678 
#469 

## Reproduction:
Open HoP Locker, have no budget card.

**Comment by SabreML** [comment]
It doesn't look like this is actually a bug. On base TG (and here too) the only deparment which actually gets their own departmental budget card is Cargo.

**Comment by ta3370** [comment]
Really? So there's no such thing as Budgets?

**Comment by gonenoculer5** [comment]
> Really? So there's no such thing as Budgets?

Hasn't been a thing for many many months. Was removed by TG upstream an eon ago, only cargo has a budget card now.

**Comment by gonenoculer5** [comment]
They are instead tied to head ID cards now. Accessible through IRN.
